# Setup
title:        Long LaMP
tagline:      Personalized Long-Text Generation
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Ishita Kumar, Snigdha Viswanathan, Sushrita Yerra, Alireza Salemi, Ryan A. Rossi, Franck Dernoncourt, Hanieh Deilamsalehy, Xiang Chen, Ruiyi Zhang, Shubham Agarwal, Nedim Lipka, Chien Van Nguyen, Thien Huu Nguyen, Hamed Zamani

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
